'use strict';
const $=s=>document.querySelector(s), root=$('#app'), E=LocalEngine;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>E.finite(v)?(Math.round(v*10)/10).toString():'未测得';
const uid=()=>crypto.randomUUID(), date=t=>new Date(t).toLocaleString('zh-CN');
const KEY='rehab-offline-state-1';
let data={version:1,profile:{name:'本机用户',restrictions:''},records:[],plan:null,health:[],medicines:[],notes:[],archive:[]},catalog,tab='plan',group='all',selected=null,training=null,worker=null,pending=new Map(),messageId=0,session=null,fileUrl=null,saveBusy=false,calibration=null;
let toastTimer;
let workerUrls=[];
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));return true;}catch{toast('手机存储不足，结果尚未保存。请先导出并清理旧记录。');return false;}}
function hydrate(){const raw=localStorage.getItem(KEY);if(!raw)return;try{const value=JSON.parse(raw);if(value.version!==1||!Array.isArray(value.records)||!value.profile)throw Error();data={...data,...value};}catch{throw Error('本机记录无法读取，未覆盖原记录。请保留应用数据并反馈。');}}
function getSpec(id){return [...catalog.rehab,...catalog.fitness,...catalog.posture].find(x=>x.id===id);}
function setTab(next){if(session){toast('请先结束本次分析或跟练');return;}selected=null;training=null;group='all';tab=next;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));render();scrollTo(0,0);}
function render(){if(tab==='plan')planPage();else if(tab==='rehab'||tab==='fitness')library();else if(tab==='history')history();else healthPage();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
function library(){
 const fitness=tab==='fitness',items=fitness?catalog.fitness:catalog.rehab,groups=[['all','全部'],...new Map(items.map(x=>[fitness?x.group:x.joint,fitness?x.group:x.joint_label]))];
 root.innerHTML=`<h1>${fitness?'健身动作库':'身体评估'}</h1>${fitness?'':'<div class="row"><button id="front-posture">正面体态</button><button id="side-posture">侧面体态</button><button id="body">身体汇总</button></div>'}<input id="search" type="search" placeholder="搜索动作"><div class="library"><aside class="categories">${groups.map(([id,n])=>`<button data-group="${esc(id)}" class="${group===id?'active':''}">${esc(n)}</button>`).join('')}</aside><section id="rows"></section></div>`;
 function rows(){const query=$('#search').value.trim();$('#rows').innerHTML=items.filter(x=>(group==='all'||(fitness?x.group:x.joint)===group)&&x.label.includes(query)).map(x=>`<button class="action" data-exercise="${esc(x.id)}"><strong>${esc(x.label)}</strong><small>${esc(fitness?x.group:x.joint_label)} · ${x.view==='frontal'?'正面':'侧面'}拍摄${x.experimental?' · 观察项目':''}</small></button>`).join('')||'<p class="muted">没有找到动作</p>';document.querySelectorAll('[data-exercise]').forEach(b=>b.onclick=()=>detail(b.dataset.exercise));}
 $('#search').oninput=rows;document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{group=b.dataset.group;library();});
 if(!fitness){$('#front-posture').onclick=()=>detail('posture_front');$('#side-posture').onclick=()=>detail('posture_side');$('#body').onclick=bodyPage;}rows();
}
function detail(id,item=null){
 selected=getSpec(id);training=item;const s=selected,i=s.instructions;
 root.innerHTML=`<button id="back">返回${item?'训练':'动作库'}</button><h1>${esc(s.label)}</h1><p class="muted">${s.view==='frontal'?'正面':'侧面'}拍摄 · 手机本地分析</p><section class="card"><h2>怎么做</h2>${(i?[i.start,i.move,i.return]:s.steps).map((text,n)=>`<div class="steps"><b>${n+1}</b><p>${esc(text)}</p></div>`).join('')}<details><summary>拍摄与测量说明</summary><p>${esc(i?.camera||s.camera||'手机放稳，保持自然站姿。')}</p><p>${esc(i?.boundary||s.note||'这是画面中的二维观察，不作诊断。')}</p><p>开始时停留约 1 秒。建议录制 15–40 秒，最长 120 秒。</p></details></section>${item?`<section class="card"><h2>本次训练</h2><p>${item.reps} 次 × 1 组${item.target!==null?' · 目标 '+num(item.target)+'°':''}</p></section>`:''}<section class="card"><label for="side">测试侧（本人左右）</label><select id="side"><option value="left">本人左侧</option><option value="right">本人右侧</option></select><button class="primary" id="capture">拍摄视频</button><button class="secondary" id="choose">选择已有视频</button>${id.startsWith('posture_')?'':'<button class="secondary" id="live">打开相机跟练</button>'}<input id="capture-file" type="file" accept="video/*" capture="environment" hidden><input id="choose-file" type="file" accept="video/*" hidden><div id="file-area"></div></section><p class="safety">疼痛、头晕或不适时立即停止。不为追求角度勉强活动。</p>`;
 $('#back').onclick=()=>{selected=null;training=null;render();};if(item){$('#side').value=item.side;$('#side').disabled=true;}
 $('#capture').onclick=()=>$('#capture-file').click();$('#choose').onclick=()=>$('#choose-file').click();
 for(const input of ['#capture-file','#choose-file'])$(input).onchange=()=>selectFile($(input).files?.[0]);
 if($('#live'))$('#live').onclick=()=>livePage($('#side').value);
}
function selectFile(file){
 if(!file)return;if(file.size>256*1024*1024){toast('录像超过 256 MB，请裁短后重试');return;}
 calibration=null;if(fileUrl)URL.revokeObjectURL(fileUrl);fileUrl=URL.createObjectURL(file);
 $('#file-area').innerHTML='<div class="stage"><video id="preview" playsinline controls></video></div><p class="muted" id="file-name"></p><button class="primary" id="analyze">开始分析</button>';
 $('#preview').src=fileUrl;$('#file-name').textContent=file.name+' · '+num(file.size/1048576)+' MB';$('#analyze').onclick=()=>analyzeFile(file,$('#side').value);
 if(['fitness_squat','fitness_deadlift','fitness_bench_press','fitness_row','fitness_overhead_press','fitness_curl'].includes(selected.id)){
  $('#file-area').insertAdjacentHTML('beforeend','<details><summary>同时分析器械速度与功率</summary><p>先选器械上的清晰位置，再选同一平面内标尺的两个端点。使用录像开始画面。</p><button class="secondary" id="calibrate">在画面中选三个点</button><p id="calibration-status" class="muted">未标定</p><label>标尺长度（厘米）<input id="ruler" type="number" min="5" max="500" value="100"></label><label>器械总质量（kg，可不填）<input id="mass" type="number" min="0.1" max="500" step="any"></label><label class="check"><input id="plane-ok" type="checkbox">手机固定，标尺与器械运动在同一平面，器械为自由重量</label></details>');
  $('#calibrate').onclick=async()=>{try{const v=$('#preview');v.pause();if(v.currentTime>.001)await waitEvent(v,'seeked',()=>v.currentTime=0);if(!v.videoWidth)throw Error('请等录像画面出现后再标定');const pts=[];$('#calibration-status').textContent='点击器械跟踪点';v.controls=false;v.onclick=e=>{const rect=v.getBoundingClientRect(),scale=Math.min(rect.width/v.videoWidth,rect.height/v.videoHeight),drawW=v.videoWidth*scale,drawH=v.videoHeight*scale,x=(e.clientX-rect.left-(rect.width-drawW)/2)/drawW,y=(e.clientY-rect.top-(rect.height-drawH)/2)/drawH;if(x<0||x>=1||y<0||y>=1)return;pts.push([x,y]);$('#calibration-status').textContent=pts.length===1?'点击标尺第一个端点':pts.length===2?'点击标尺第二个端点':'三个点已选好';if(pts.length===3){calibration={points:pts};v.onclick=null;v.controls=true;}};}catch(e){toast(e.message);}};
 }
}
function requestWorker(type,params={},transfer=[]){
 if(!worker)throw Error('本地模型尚未准备');
 return new Promise((resolve,reject)=>{const id=++messageId,timer=setTimeout(()=>{pending.delete(id);reject(Error('本地分析超时，请结束后重试'));},type==='init'?90000:30000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,type,...params},transfer);});
}
async function initModel(spec,calibration=null){
 killWorker();
 const mode=spec.joint==='finger'?'hand':spec.joint==='wrist'?'wrist':'pose';
 const load=async(path,binary=false)=>{const response=await fetch(path);if(!response.ok)throw Error('安装包中的模型资源不完整');return binary?response.arrayBuffer():response.text();};
 const [vision,tracker,code,simdJs,noSimdJs,simdBinary,noSimdBinary,poseModel,handModel,manifest]=await Promise.all([
  load('vendor/vision_bundle.js'),load('barbell.js'),load('worker.js'),load('vendor/wasm/vision_wasm_internal.js'),load('vendor/wasm/vision_wasm_nosimd_internal.js'),load('vendor/wasm/vision_wasm_internal.wasm',true),load('vendor/wasm/vision_wasm_nosimd_internal.wasm',true),mode==='hand'?null:load('models/pose_landmarker_full.task',true),mode==='pose'?null:load('models/hand_landmarker.task',true),load('models/manifest.json')]);
 const url=(bytes,type)=>{const value=URL.createObjectURL(new Blob([bytes],{type}));workerUrls.push(value);return value;};
 const simd={wasmLoaderPath:url(simdJs,'text/javascript'),wasmBinaryPath:url(simdBinary,'application/wasm')},noSimd={wasmLoaderPath:url(noSimdJs,'text/javascript'),wasmBinaryPath:url(noSimdBinary,'application/wasm')};
 worker=new Worker(url('self.exports={};\n'+vision+'\n'+tracker+'\n'+code,'text/javascript'));
 worker.onmessage=({data})=>{const job=pending.get(data.id);if(!job)return;clearTimeout(job.timer);pending.delete(data.id);data.ok?job.resolve(data):job.reject(Error(data.error));};
 worker.onerror=event=>{console.error('Model worker failed',event.message,event.filename,event.lineno);for(const job of pending.values()){clearTimeout(job.timer);job.reject(Error('本地模型启动失败：'+(event.message||'请检查系统 WebView 版本')));}pending.clear();killWorker();};
 const transfer=[poseModel,handModel].filter(Boolean);return requestWorker('init',{mode,calibration,simd,noSimd,poseModel,handModel,modelInfo:JSON.parse(manifest)},transfer);
}
function killWorker(){worker?.terminate();worker=null;for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('已停止'));}pending.clear();workerUrls.forEach(url=>URL.revokeObjectURL(url));workerUrls=[];}
function waitEvent(element,name,action,timeout=20000){return new Promise((resolve,reject)=>{const done=()=>{clean();resolve();},bad=()=>{clean();reject(Error('这段录像不能解码，请用相机录制 MP4 后重试'));},timer=setTimeout(()=>{clean();reject(Error('读取录像超时'));},timeout);function clean(){clearTimeout(timer);element.removeEventListener(name,done);element.removeEventListener('error',bad);}element.addEventListener(name,done,{once:true});element.addEventListener('error',bad,{once:true});action();});}
function stage(spec,isLive){root.innerHTML=`<h1>${esc(spec.label)}</h1><div class="stage"><video id="motion-video" playsinline muted></video><canvas id="overlay"></canvas></div><div class="guidance" id="hint">正在准备手机模型…</div><div class="stats"><div><b id="rep-count">0</b><span>已完成</span></div><div><b id="angle">—</b><span>投影角度 °</span></div><div><b id="elapsed">0</b><span>秒</span></div></div><progress class="progress" id="progress" value="0" max="1"></progress><button class="secondary" id="stop">${isLive?'结束并保存':'取消分析'}</button>`;}
function draw(result,width,height){const canvas=$('#overlay');if(!canvas)return;canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.strokeStyle='#65edb8';ctx.fillStyle='#65edb8';ctx.lineWidth=3;
 const p=E.points(result,width,height);for(const [a,b]of [['left_shoulder','right_shoulder'],['left_shoulder','left_elbow'],['left_elbow','left_wrist'],['right_shoulder','right_elbow'],['right_elbow','right_wrist'],['left_hip','left_knee'],['left_knee','left_ankle'],['right_hip','right_knee'],['right_knee','right_ankle']])if(p[a]&&p[b]){ctx.beginPath();ctx.moveTo(...p[a]);ctx.lineTo(...p[b]);ctx.stroke();}
 for(const point of Object.values(p)){ctx.beginPath();ctx.arc(...point,4,0,Math.PI*2);ctx.fill();}if(result.hand)for(const point of result.hand){ctx.beginPath();ctx.arc(point.x*width,point.y*height,3,0,Math.PI*2);ctx.fill();}}
function updateView(observation,result,t,width,height){if(!$('#hint'))return;$('#hint').textContent=observation.hint;$('#rep-count').textContent=observation.reps;$('#angle').textContent=observation.value===null?'—':num(observation.value);$('#elapsed').textContent=Math.floor(t);draw(result,width,height);}
async function decodedVideoBitmap(video){
 // Android may emit seeked before the decoder has presented the requested frame.
 // Read only current decoded data; never substitute a blank image or skip time.
 const deadline=performance.now()+10000;
 while(video.seeking||video.readyState<2||!video.videoWidth){
  if(video.error)throw Error('这段录像不能解码，请换用相机录制的 MP4');
  if(session?.cancelled)throw Error('已停止');
  if(performance.now()>deadline)throw Error('等待录像画面超时，请重新选择录像');
  await new Promise(resolve=>setTimeout(resolve,20));
 }
 const scale=Math.min(1,768/video.videoWidth),width=Math.round(video.videoWidth*scale),height=Math.round(video.videoHeight*scale);
 // Canvas capture also supports WebViews that reject createImageBitmap(video).
 const canvas=new OffscreenCanvas(width,height);canvas.getContext('2d').drawImage(video,0,0,width,height);
 return {bitmap:canvas.transferToImageBitmap(),width,height};
}
async function frame(video,t,spec,side,engine,samples=null){const {bitmap,width,height}=await decodedVideoBitmap(video);const {result}=await requestWorker('frame',{image:bitmap,timestamp:t*1000},[bitmap]);const raw=E.measure(spec,side,result,width,height);if(samples)samples.push([t,raw]);const observation=engine.consume(t,raw);updateView(observation,result,t,width,height);return observation;}
async function analyzeFile(file,side){
 const spec=selected,item=training,token={cancelled:false};let bar=null;
 if(calibration&&$('#ruler')){const meters=Number($('#ruler').value)/100,kg=$('#mass').value?Number($('#mass').value):null;if(!$('#plane-ok').checked||!E.finite(meters)||meters<.05||meters>5||kg!==null&&(!E.finite(kg)||kg<=0||kg>500)){toast('请核对标尺、质量和自由重量条件');return;}bar={...calibration,meters,kg};}
 session=token;stage(spec,false);const video=$('#motion-video');
 $('#stop').onclick=()=>{token.cancelled=true;killWorker();};
 try {
  await waitEvent(video,'loadeddata',()=>{video.src=fileUrl;video.load();});if(!E.finite(video.duration)||video.duration<=0||video.duration>120.1)throw Error('请选择 120 秒以内的完整录像');
  const model=await initModel(spec,bar);if(token.cancelled)return;const engine=new E.Engine(spec,side,item?.target??null),samples=[];const end=video.duration;
  // Timestamp follows the browser media timeline, never inference time or guessed FPS.
  for(let target=0;target<end-.04;target+=.12){if(token.cancelled)break;if(video.readyState<2||Math.abs(video.currentTime-target)>.001)await waitEvent(video,'seeked',()=>video.currentTime=target);const t=video.currentTime;if(engine.last===null||t>engine.last)await frame(video,t,spec,side,engine,samples);$('#progress').value=target/end;await new Promise(resolve=>setTimeout(resolve,0));}
  if(!token.cancelled){const report=E.analyzeReplay(spec,side,samples,item?.target??null);if(bar)report.barbell=(await requestWorker('barbell-report')).report;await finishRecord(spec,side,report,item,'REPLAY_FILE',model.models);}
 } catch(error){if(!token.cancelled){toast(error.message);root.innerHTML=`<section class="card"><h2>未完成分析</h2><p class="error">${esc(error.message)}</p><button class="primary" id="again">返回动作</button></section>`;$('#again').onclick=()=>detail(spec.id,item);}}
 finally{session=null;killWorker();video.pause();video.removeAttribute('src');video.load();if(token.cancelled)detail(spec.id,item);}
}
async function livePage(side){
 const spec=selected,item=training,token={cancelled:false,stream:null,started:false};session=token;stage(spec,true);const video=$('#motion-video');$('#progress').hidden=true;
 $('#stop').disabled=true;$('#stop').textContent='停止';$('#stop').onclick=()=>{token.cancelled=true;token.wake?.();};
 try {
  if(!navigator.mediaDevices?.getUserMedia)throw Error('当前系统 WebView 不支持相机，请更新或使用录像分析');
  const model=await initModel(spec);token.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'user',width:{ideal:640},height:{ideal:480}}});if(token.cancelled)return;
  video.srcObject=token.stream;await video.play();video.classList.add('mirrored');$('#overlay').classList.add('mirrored');$('#hint').textContent='手机放稳，点击开始';
  const start=document.createElement('button');start.className='primary';start.textContent='开始跟练';root.insertBefore(start,$('#stop'));$('#stop').disabled=false;
  await new Promise(resolve=>{start.onclick=()=>{token.started=true;resolve();};token.wake=resolve;});start.remove();if(token.cancelled)return;
  const engine=new E.Engine(spec,side,item?.target??null);const began=performance.now();let lastVideo=-1;
  while(!token.cancelled){const t=(performance.now()-began)/1000;if(t>120)break;if(video.currentTime!==lastVideo&&video.readyState>=2){lastVideo=video.currentTime;await frame(video,t,spec,side,engine);if(item&&engine.reps.filter(r=>r.targetMet!==false).length>=item.reps)break;}await new Promise(resolve=>setTimeout(resolve,80));}
  token.stream.getTracks().forEach(t=>t.stop());video.srcObject=null;await finishRecord(spec,side,engine.report(),item,'LIVE_CAMERA',model.models);
 } catch(error){if(!token.cancelled)toast(error.message);detail(spec.id,item);}
 finally{token.stream?.getTracks().forEach(t=>t.stop());video.srcObject=null;session=null;killWorker();if(!token.started)detail(spec.id,item);}
}
window.offlinePause=()=>{if(session){session.cancelled=true;session.wake?.();session.stream?.getTracks().forEach(t=>t.stop());}};
window.offlineBack=()=>{if(session){if(confirm('结束当前动作？')){session.cancelled=true;session.wake?.();}return true;}if(selected){selected=null;training=null;render();return true;}if(tab!=='plan'){setTab('plan');return true;}return false;};
async function finishRecord(spec,side,report,item,source,models){
 const kind=item?'training':spec.id.startsWith('fitness_')?'fitness':spec.id.startsWith('posture_')?'posture':'assessment';
 const record={id:uid(),exercise:spec.id,side,kind,created:Date.now(),source,report,models:Object.fromEntries(Object.entries(models.models).map(([key,value])=>[key,value.sha256])),planId:item?data.plan?.id:null};
 if(data.records.length>=250)throw Error('本机已有 250 条活动记录。请先导出并清理不再需要的记录，不会自动删除旧结果。');
 data.records.push(record);if(!save()){data.records.pop();throw Error('结果保存失败，未记为完成');}
 selected=null;reportPage(record,item);
}
function reportPage(record,item=null){
 const spec=getSpec(record.exercise),r=record.report,rows=r.metrics?Object.entries(r.metrics).map(([key,value])=>`<div class="metric"><span>${esc(catalog.posture_metrics[key]?.[0]||key)}</span><b>${num(value)} ${esc(catalog.posture_metrics[key]?.[1]||'')}</b></div>`).join(''):`<div class="stats"><div><b>${r.reps.length}</b><span>完整动作 次</span></div><div><b>${num(r.max===null?null:r.max-r.min)}</b><span>投影活动幅度 °</span></div><div><b>${num(r.validRatio*100)}%</b><span>有效观察时间</span></div></div><div class="metric"><span>最小 / 最大投影角</span><b>${num(r.min)} / ${num(r.max)}°</b></div><div class="metric"><span>每次平均用时</span><b>${num(r.meanDuration)} 秒</b></div><canvas class="plot" id="plot"></canvas>`;
 root.innerHTML=`<button id="back-records">返回记录</button><h1>${esc(spec.label)} · ${record.kind==='training'?'训练':'结果'}</h1><p class="muted">${record.side==='left'?'本人左侧':'本人右侧'} · ${date(record.created)}</p><section class="card">${rows}<p>${r.metrics?'记录自然站姿中的可见体表投影。':r.reps.length?`本次观察到 ${r.reps.length} 次完整往返，活动范围为 ${num(r.min)}° 至 ${num(r.max)}°。`:'这段录像没有观察到完整往返。已记录的可见角度仍保留，可调整拍摄位置后再测。'}</p><details><summary>测量说明</summary><p>手机本地 MediaPipe 模型，${esc(r.contract)}。角度为画面中的二维投影，不是临床关节活动度；有效观察比例不是准确率。缺测不补值，不估计真实肌肉力量。</p><p>${esc(spec.note||spec.instructions?.boundary||'')}</p></details></section>${record.kind==='training'?`<form class="card" id="feedback"><h2>训练感受</h2><label>疼痛或不适（0–10）<input id="pain" type="number" min="0" max="10" step="1" value="${record.feedback?.pain??0}" required></label><label>疲劳（0–10）<input id="fatigue" type="number" min="0" max="10" step="1" value="${record.feedback?.fatigue??0}" required></label><button class="primary">保存感受</button></form>`:''}<button class="secondary" id="export">导出报告</button>${record.kind==='assessment'?'<button class="primary" id="make-plan">根据评估安排训练</button>':''}<p class="safety">疼痛、头晕或不适时停止，必要时咨询专业人员。</p>`;
 $('#back-records').onclick=()=>setTab('history');$('#export').onclick=()=>exportJson({type:'rehab-offline-report',record});
 const remove=document.createElement('button');remove.className='secondary';remove.textContent='删除这条记录';remove.onclick=()=>{if(data.plan?.items.some(x=>x.assessment===record.id||x.training===record.id)){toast('此记录仍是当前计划依据，请保留');return;}if(!confirm('删除这条活动记录？建议先导出报告，删除后无法恢复。'))return;const before=data.records;data.records=data.records.filter(x=>x.id!==record.id);if(!save()){data.records=before;return;}setTab('history');};root.append(remove);
 if(r.barbell){const bar=document.createElement('section');bar.className='card';bar.innerHTML=`<h2>器械运动</h2>${r.barbell.valid?`<div class="metric"><span>峰值速度</span><b>${num(r.barbell.peakSpeed)} m/s</b></div><div class="metric"><span>峰值加速度</span><b>${num(r.barbell.peakAcceleration)} m/s²</b></div><div class="metric"><span>峰值器械外力（估算）</span><b>${num(r.barbell.peakForce)} N</b></div><div class="metric"><span>峰值器械功率（估算）</span><b>${num(r.barbell.peakPower)} W</b></div><details><summary>估算说明</summary><p>${esc(r.barbell.note)}</p><p>跟踪覆盖 ${num(r.barbell.coverage*100)}%，不是准确率。</p></details>`:`<p>${esc(r.barbell.note)}</p>`}`;$('#export').before(bar);}
 if($('#make-plan'))$('#make-plan').onclick=()=>setTab('plan');if($('#plot'))plot(r.series);
 if($('#feedback'))$('#feedback').onsubmit=e=>{e.preventDefault();const pain=Number($('#pain').value),fatigue=Number($('#fatigue').value);if(![pain,fatigue].every(x=>Number.isInteger(x)&&x>=0&&x<=10)){toast('请填写 0–10 的整数');return;}
 const before=JSON.stringify(data);record.feedback={pain,fatigue};const bound=item||data.plan?.items.find(x=>x.exercise===record.exercise&&x.side===record.side);
 if(bound&&record.planId===data.plan?.id&&pain===0&&fatigue<5&&r.reps.filter(x=>x.targetMet!==false).length>=bound.reps&&r.validRatio>=.8){bound.complete=true;bound.training=record.id;}
 if(!save()){data=JSON.parse(before);return;}toast(pain>0||fatigue>=5?'已保存，请先休息，不继续自动训练':'已保存训练感受');setTab('plan');};
}
function plot(series){if(!series?.length)return;const c=$('#plot');c.width=700;c.height=180;const ctx=c.getContext('2d'),max=Math.max(...series.map(x=>x[1])),min=Math.min(...series.map(x=>x[1])),duration=series.at(-1)[0]-series[0][0]||1;ctx.strokeStyle='#159b73';ctx.lineWidth=3;ctx.beginPath();series.forEach(([t,v],i)=>{const x=(t-series[0][0])/duration*690+5,y=170-(v-min)/(max-min||1)*160;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}
function history(){root.innerHTML=`<h1>我的活动记录</h1>${[...data.records].reverse().map(r=>`<button class="record" data-record="${r.id}"><strong>${esc(getSpec(r.exercise)?.label||r.exercise)} · ${{assessment:'评估',training:'训练',fitness:'健身',posture:'体态'}[r.kind]}</strong><small>${date(r.created)} · ${r.side==='left'?'左侧':'右侧'}</small></button>`).join('')||'<section class="card"><p>完成一次评估或训练后，结果会保存在这里。</p><button class="primary" id="go-assess">开始评估</button></section>'}`;document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>reportPage(data.records.find(x=>x.id===b.dataset.record)));if($('#go-assess'))$('#go-assess').onclick=()=>setTab('rehab');}
function bodyPage(){const latest=new Map();for(const r of data.records.filter(x=>x.kind==='assessment'))latest.set(r.exercise+':'+r.side,r);root.innerHTML=`<button id="body-back">返回评估</button><h1>身体汇总</h1><p class="muted">${esc(data.profile.name)} · 最近一次各项评估</p>${[...latest.values()].map(r=>`<section class="card"><h2>${esc(getSpec(r.exercise).label)} · ${r.side==='left'?'左侧':'右侧'}</h2><p>投影范围 ${num(r.report.min)}°–${num(r.report.max)}°，完整动作 ${r.report.reps.length} 次。</p><small>${date(r.created)}</small></section>`).join('')||'<p>先完成一次评估。</p>'}`;$('#body-back').onclick=()=>setTab('rehab');}
function planPage(){
 const proposal=E.propose(data.records,catalog,Date.now(),data.profile),plan=data.plan,remaining=plan?.items.find(x=>!x.complete),blocked=data.records.filter(x=>x.kind==='training').sort((a,b)=>b.created-a.created)[0]?.feedback;
 root.innerHTML=`<h1>今天的训练</h1><section class="card"><span class="badge">${plan?'根据本人评估安排':'从一次评估开始'}</span><h2>${plan?'基础活动计划':'先了解身体活动情况'}</h2><p>${plan?`${plan.items.filter(x=>x.complete).length} / ${plan.items.length} 项已完成`:'评估完成后，按本次观察到的动作和次数安排练习。'}</p>${plan?plan.items.map(x=>`<div class="plan-item"><strong>${esc(getSpec(x.exercise).label)} · ${x.side==='left'?'左侧':'右侧'}</strong><small>${x.reps} 次 × 1 组${x.target!==null?' · '+num(x.target)+'°':''}</small><p class="${x.complete?'training-complete':''}">${x.complete?'本轮已完成':x===remaining?'接下来做这一项':'稍后练习'}</p></div>`).join(''):''}<button class="primary" id="plan-main">${remaining?'开始下一项训练':plan?'重新评估或安排下一轮':'开始身体评估'}</button></section><section class="card"><h2>${plan?'下一轮安排':'生成训练计划'}</h2><p>${proposal.items.length?`可安排 ${proposal.items.length} 项，每项 1 组，次数不超过本次评估已完成次数。`:'先完成一次有完整动作的评估。'}</p>${proposal.items.length?`<form id="plan-form"><label class="check"><input type="checkbox" id="general-ok" required>当前没有不适或医嘱限制，适合一般活动</label>${proposal.items.some(x=>x.standing)?'<label class="check"><input type="checkbox" id="support-ok" required>站立动作有稳固支撑，必要时有人陪同</label>':''}<button class="secondary">${plan?'安排下一轮':'生成并保存计划'}</button></form>`:''}<details><summary>安排依据与未纳入项目</summary><p>使用本人 7 天内的最新手机评估，每次最多 4 项；有效观察时间至少 80%，不自动加量。一般活动建议，不是疾病或术后处方。</p>${proposal.items.map(x=>`<p>${esc(getSpec(x.exercise).label)}：${esc(x.source.title)}${x.evidenceKind==='personal-adaptation'?'（本人评估适配，不是指南具体剂量）':''}</p>`).join('')}${proposal.excluded.map(x=>`<p>${esc(x)}</p>`).join('')}</details></section>`;
 if($('#plan-form'))$('#plan-form').insertAdjacentHTML('beforeend',`<details><summary>调整本轮次数</summary>${proposal.items.map((x,i)=>`<label>${esc(getSpec(x.exercise).label)}<select id="dose-${i}">${Array.from({length:x.reps},(_,n)=>`<option value="${n+1}" ${n+1===x.reps?'selected':''}>${n+1} 次</option>`).join('')}</select></label>`).join('')}</details>`);
 $('#plan-main').onclick=()=>{if(remaining){if(blocked&&(blocked.pain>0||blocked.fatigue>=5)){toast('上次有不适或明显疲劳，请先处理原因后再练习');return;}const latest=E.propose(data.records,catalog,Date.now(),data.profile).items.find(x=>x.exercise===remaining.exercise&&x.side===remaining.side);if(!latest||latest.assessment!==remaining.assessment){toast('评估依据已变化，请重新安排计划');return;}detail(remaining.exercise,remaining);}else setTab('rehab');};
 if($('#plan-form'))$('#plan-form').onsubmit=e=>{e.preventDefault();let items;try{items=reducedPlan(proposal.items,i=>Number($('#dose-'+i).value));}catch(error){toast(error.message);return;}if(plan?.items.some(x=>!x.complete)&&!confirm('当前还有未完成项目，改为新一轮计划？'))return;const old=data.plan;data.plan={id:uid(),created:Date.now(),contract:E.VERSION,items};if(!save()){data.plan=old;return;}planPage();};
}
function reducedPlan(items,read){return items.map((x,i)=>{const reps=read(i);if(!Number.isInteger(reps)||reps<1||reps>x.reps)throw Error('本轮次数只能在已评估次数内减少');return {...x,reps};});}
function exportJson(value){if(window.OfflineAndroid?.saveJson)OfflineAndroid.saveJson(JSON.stringify(value));else toast('请在 Android 安装包中导出');}
function validateBackup(value){
 const bad=()=>{throw Error('不是此版本的有效备份，未修改本机记录');},obj=x=>x&&typeof x==='object'&&!Array.isArray(x),text=(x,max)=>typeof x==='string'&&x.length<=max,id=x=>typeof x==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(x),time=x=>E.finite(x)&&x>=0;
 const d=value?.data;if(value?.type!=='rehab-offline-backup'||value.version!==1||!obj(d)||d.version!==1||!obj(d.profile)||!text(d.profile.name,40)||!text(d.profile.restrictions,300))bad();
 for(const key of ['records','health','medicines','notes'])if(!Array.isArray(d[key])||d[key].length>(key==='records'?250:1000))bad();
 const seen=new Set();for(const r of d.records){const q=r?.report;if(!obj(r)||!id(r.id)||seen.has(r.id)||!getSpec(r.exercise)||!['left','right'].includes(r.side)||!['assessment','training','fitness','posture'].includes(r.kind)||!time(r.created)||!obj(q)||q.contract!==E.VERSION)bad();seen.add(r.id);
  if(q.metrics){if(!obj(q.metrics)||Object.values(q.metrics).some(x=>x!==null&&!E.finite(x)))bad();}
  else {if(!Array.isArray(q.reps)||q.reps.length>1000||!Array.isArray(q.series)||q.series.length>10000||!E.finite(q.validRatio)||q.validRatio<0||q.validRatio>1||!time(q.duration)||[q.min,q.max,q.baseline].some(x=>x!==null&&!E.finite(x)))bad();for(const pair of q.series)if(!Array.isArray(pair)||pair.length!==2||!time(pair[0])||!E.finite(pair[1]))bad();for(const rep of q.reps)if(!obj(rep)||!E.finite(rep.peak)||!time(rep.duration)||!time(rep.time))bad();}
  if(r.feedback&&!['pain','fatigue'].every(k=>Number.isInteger(r.feedback[k])&&r.feedback[k]>=0&&r.feedback[k]<=10))bad();
 }
 if(d.health.some(x=>!obj(x)||!text(x.name,80)||!time(x.value)||!time(x.created))||d.notes.some(x=>!obj(x)||!text(x.text,1000)||!time(x.created))||d.medicines.some(x=>!obj(x)||!id(x.id)||!text(x.name,80)||!text(x.dose,200)||typeof x.active!=='boolean'||x.taken!==undefined&&!text(x.taken,40)))bad();
 if(d.plan!==null){if(!obj(d.plan)||!id(d.plan.id)||d.plan.contract!==E.VERSION||!time(d.plan.created)||!Array.isArray(d.plan.items)||d.plan.items.length>4)bad();for(const x of d.plan.items)if(!obj(x)||!getSpec(x.exercise)||!['left','right'].includes(x.side)||!seen.has(x.assessment)||!Number.isInteger(x.reps)||x.reps<1||x.reps>5||x.sets!==1||typeof x.complete!=='boolean'||x.target!==null&&!E.finite(x.target)||!obj(x.source)||!text(x.source.title,500))bad();}
 return {version:1,profile:d.profile,records:d.records,plan:d.plan,health:d.health,medicines:d.medicines,notes:d.notes,archive:[]};
}
function healthPage(){root.innerHTML=`<h1>我的</h1><section class="card"><h2>${esc(data.profile.name)}</h2><button class="secondary" id="profile">个人信息</button><button class="secondary" id="metrics">健康指标</button><button class="secondary" id="medicines">用药记录</button><button class="secondary" id="notes">感受记录</button><button class="secondary" id="archives">健康资料</button><button class="secondary" id="backup">导出本机备份</button><button class="secondary" id="restore">恢复空档案</button><input id="restore-file" type="file" accept="application/json" hidden></section><section class="card"><h2>关于本地版</h2><p>模型、分析和记录均在这台手机上。没有账号登录，不上传录像或健康资料。</p><p class="muted">0.1.0 · Android 10 及以上<br>双摄像头、网络摄像头、家庭在线分享、语音转写和资料 OCR 尚未迁入此版。</p></section>`;
 $('#profile').onclick=profilePage;$('#metrics').onclick=metricsPage;$('#medicines').onclick=medicinesPage;$('#notes').onclick=notesPage;$('#archives').onclick=archivesPage;$('#backup').onclick=()=>exportJson({type:'rehab-offline-backup',version:1,created:Date.now(),data:{...data,archive:[]},note:'资料附件需单独保留，本备份包含评估、计划、健康指标、用药和感受。'});$('#restore').onclick=()=>$('#restore-file').click();$('#restore-file').onchange=async()=>{try{if(data.records.length||data.health.length||data.medicines.length||data.notes.length||data.archive.length||data.plan)throw Error('恢复仅用于空档案，不覆盖已有记录');const file=$('#restore-file').files[0];if(!file||file.size>4*1024*1024)throw Error('备份文件过大');const restored=validateBackup(JSON.parse(await file.text()));if(!confirm('将备份恢复到本机？'))return;const before=data;data=restored;if(!save())data=before;else {toast('已恢复');healthPage();}}catch(e){toast(e.message);}};
}
function profilePage(){root.innerHTML=`<button id="back-health">返回我的</button><h1>个人信息</h1><form class="card" id="profile-form"><label>称呼<input id="name" maxlength="40" required value="${esc(data.profile.name)}"></label><label>年龄<input id="age" type="number" min="1" max="120" value="${esc(data.profile.age||'')}"></label><label>活动限制或医嘱<textarea id="restrictions" maxlength="300">${esc(data.profile.restrictions)}</textarea></label><button class="primary">保存</button></form>`;$('#back-health').onclick=healthPage;$('#profile-form').onsubmit=e=>{e.preventDefault();const old=data.profile;data.profile={name:$('#name').value.trim(),age:Number($('#age').value)||null,restrictions:$('#restrictions').value.trim()};if(!save())data.profile=old;else{toast('已保存');healthPage();}};}
const HEALTH_METRICS=[['血压（收缩压）','mmHg'],['血压（舒张压）','mmHg'],['血糖','mmol/L'],['心率','次/分'],['体重','kg'],['血氧','%'],['体温','℃'],['睡眠','小时'],['步数','步'],['活动时长','分钟']];
function metricsPage(){root.innerHTML=`<button id="back-health">返回我的</button><h1>健康指标</h1><form class="card" id="metric-form"><label>指标<select id="metric-name">${HEALTH_METRICS.map(([n,u])=>`<option>${n} · ${u}</option>`).join('')}</select></label><label>数值<input id="metric-value" type="number" min="0" step="any" required></label><button class="primary">记录</button></form><section class="card">${[...data.health].reverse().slice(0,40).map(x=>`<div class="metric"><span>${esc(x.name)}<br><small>${date(x.created)}</small></span><b>${num(x.value)}</b></div>`).join('')||'<p>暂无记录</p>'}</section>`;$('#back-health').onclick=healthPage;$('#metric-form').onsubmit=e=>{e.preventDefault();const value=Number($('#metric-value').value);if(!E.finite(value)||value<0)return;data.health.push({name:$('#metric-name').value,value,created:Date.now()});if(save())metricsPage();else data.health.pop();};}
function medicinesPage(){root.innerHTML=`<button id="back-health">返回我的</button><h1>用药记录</h1><form class="card" id="medicine-form"><label>药物名称<input id="medicine-name" maxlength="80" required></label><label>医嘱用法<input id="medicine-dose" maxlength="200" required placeholder="按原医嘱填写"></label><button class="primary">添加</button></form><section class="card">${data.medicines.map(m=>`<div class="plan-item"><strong>${esc(m.name)}</strong><p>${esc(m.dose)}</p><small>${m.active?'使用中':'已停用'}${m.taken?.slice(0,10)===new Date().toISOString().slice(0,10)?' · 今日已记录服用':''}</small><div class="row"><button data-take="${m.id}" ${m.active?'':'disabled'}>记录今日服用</button><button data-med="${m.id}">${m.active?'停用':'恢复记录'}</button></div></div>`).join('')||'<p>暂无记录</p>'}<p class="safety">只记录原医嘱，不建议加药、停药或调整剂量。</p></section>`;$('#back-health').onclick=healthPage;$('#medicine-form').onsubmit=e=>{e.preventDefault();data.medicines.push({id:uid(),name:$('#medicine-name').value.trim(),dose:$('#medicine-dose').value.trim(),active:true});if(save())medicinesPage();else data.medicines.pop();};document.querySelectorAll('[data-med]').forEach(b=>b.onclick=()=>{const m=data.medicines.find(x=>x.id===b.dataset.med);m.active=!m.active;if(!save())m.active=!m.active;medicinesPage();});document.querySelectorAll('[data-take]').forEach(b=>b.onclick=()=>{const m=data.medicines.find(x=>x.id===b.dataset.take),old=m.taken;m.taken=new Date().toISOString();if(!save())m.taken=old;medicinesPage();});}
function notesPage(){root.innerHTML=`<button id="back-health">返回我的</button><h1>感受记录</h1><form class="card" id="note-form"><textarea id="note" maxlength="1000" required placeholder="记录今天的身体感受"></textarea><button class="primary">保存</button></form>${[...data.notes].reverse().map(x=>`<section class="card"><p>${esc(x.text)}</p><small>${date(x.created)}</small></section>`).join('')}`;$('#back-health').onclick=healthPage;$('#note-form').onsubmit=e=>{e.preventDefault();data.notes.push({text:$('#note').value.trim(),created:Date.now()});if(save())notesPage();else data.notes.pop();};}
function archiveDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open('rehab-offline-documents',1);request.onupgradeneeded=()=>request.result.createObjectStore('files');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('无法打开资料存储'));});}
async function archiveOp(method,id,value){const db=await archiveDB();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('files',method==='get'?'readonly':'readwrite'),store=tx.objectStore('files'),r=method==='get'?store.get(id):store[method](...(method==='put'?[value,id]:[id]));tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(Error('资料保存失败，手机可能存储不足'));tx.onabort=()=>reject(Error('资料保存未完成'));});}finally{db.close();}}
function archivesPage(){root.innerHTML=`<button id="back-health">返回我的</button><h1>健康资料</h1><section class="card"><label>添加资料（PDF、图片或文本，单份最多 8 MB）<input id="archive-file" type="file" accept="application/pdf,image/jpeg,image/png,text/plain"></label><button class="primary" id="archive-add">保存到手机</button></section><section class="card">${data.archive.map(a=>`<div class="plan-item"><strong>${esc(a.name)}</strong><small>${num(a.size/1024)} KB · ${a.trashed?'回收站':'本机资料'}</small><div class="row">${a.trashed?'':`<button data-document="${a.id}">导出原文件</button>`}<button data-archive="${a.id}">${a.trashed?'恢复':'移入回收站'}</button></div></div>`).join('')||'<p>暂无资料</p>'}</section>`;$('#back-health').onclick=healthPage;$('#archive-add').onclick=async()=>{if(saveBusy)return;const f=$('#archive-file').files[0];if(!f)return;if(!['application/pdf','image/jpeg','image/png','text/plain'].includes(f.type)){toast('请选择 PDF、JPG、PNG 或文本文件');return;}if(f.size>8*1024*1024||data.archive.length>=50||data.archive.reduce((s,a)=>s+a.size,0)+f.size>64*1024*1024){toast('资料超出本机配额，请保留原文件');return;}saveBusy=true;try{const id=uid();await archiveOp('put',id,f);data.archive.push({id,name:f.name,size:f.size,created:Date.now(),trashed:false});if(save()){toast('已保存');archivesPage();}else{data.archive.pop();await archiveOp('delete',id);}}catch(e){toast(e.message);}finally{saveBusy=false;}};document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>{const a=data.archive.find(x=>x.id===b.dataset.archive);a.trashed=!a.trashed;if(!save())a.trashed=!a.trashed;archivesPage();});document.querySelectorAll('[data-document]').forEach(b=>b.onclick=async()=>{try{const f=await archiveOp('get',b.dataset.document);if(!f)throw Error('资料原文件暂时无法读取');const reader=new FileReader();reader.onload=()=>{if(!window.OfflineAndroid?.saveDocument){toast('请在 Android 安装包中导出');return;}OfflineAndroid.saveDocument(f.name,String(reader.result).split(',')[1],f.type);};reader.onerror=()=>toast('资料读取失败');reader.readAsDataURL(f);}catch(e){toast(e.message);}});}
(async()=>{try{if(typeof Worker==='undefined'||typeof WebAssembly==='undefined'||typeof OffscreenCanvas==='undefined'||typeof createImageBitmap==='undefined'||typeof crypto.randomUUID!=='function')throw Error('系统 WebView 版本较旧，请先通过系统正规渠道更新 Android System WebView');hydrate();catalog=await (await fetch('catalog.json')).json();render();}catch(e){root.innerHTML=`<section class="card"><h1>暂时无法打开</h1><p>${esc(e.message)}</p><p>请保留应用数据，不要卸载后再试。</p></section>`;}})();
