"""Desktop shell and layout. All actions use MainWindow's existing run gates."""
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QWidget, QFrame, QLabel, QPushButton, QLineEdit, QComboBox,
    QVBoxLayout, QHBoxLayout, QStackedWidget, QPlainTextEdit, QScrollArea, QTabWidget, QCheckBox)

from .. import __version__
from .catalog import ExerciseCatalog
from .training import TrainingControls
from .training_hub import TrainingHub
from .exercise_guide import ExerciseGuide
from .widgets import VideoCanvas, MetricCard, Disclosure, NoticeLabel
from .video_pair import VideoPairPanel
from .journey import JourneyPanel


def build_workspace(w):
    central = QWidget()
    w.setCentralWidget(central)
    root = QHBoxLayout(central)
    root.setContentsMargins(0, 0, 0, 0)
    root.setSpacing(0)
    sidebar = QFrame()
    sidebar.setObjectName('sidebar')
    sidebar.setFixedWidth(188)
    nav = QVBoxLayout(sidebar)
    nav.setContentsMargins(16, 26, 16, 22)
    nav.setSpacing(7)
    brandrow = QHBoxLayout()
    mark = QLabel('康')
    mark.setObjectName('brandMark')
    mark.setAlignment(Qt.AlignmentFlag.AlignCenter)
    mark.setFixedSize(44, 44)
    brandrow.addWidget(mark)
    brand = QLabel('康复助手')
    brand.setObjectName('brand')
    brandrow.addWidget(brand)
    nav.addLayout(brandrow)
    nav.addSpacing(34)
    label = QLabel('康复管理')
    label.setObjectName('navHeading')
    nav.addWidget(label)
    nav.addSpacing(5)

    def nav_button(label, callback, layout=nav):
        button = QPushButton(label)
        button.setObjectName('nav')
        button.setCheckable(True)
        button.setCursor(Qt.CursorShape.PointingHandCursor)
        button.clicked.connect(callback)
        layout.addWidget(button)
        return button

    w.scene_buttons = {'rehab': nav_button('身体评估', w._show_catalog)}
    w.training_nav = nav_button('训练中心', w._show_training_hub)
    w.body_nav = nav_button('身体档案', w._show_body)
    w.history_nav = nav_button('历史记录', w._history)
    w.silver_nav = nav_button('银发健康守护', lambda: w._show_silver())
    nav.addSpacing(22)
    tools = Disclosure('其他工具')
    for scene, label in (('activity', '日常活动'), ('bedroom_demo', '卧室观察演示'), ('safety_demo', '安全提示演示')):
        w.scene_buttons[scene] = nav_button(label, lambda checked=False, s=scene: w._select_scene(s), tools.box)
    w.tools_disclosure = tools
    nav.addWidget(tools)
    nav.addStretch()
    w.silver_help = QPushButton('我需要帮助')
    w.silver_help.setObjectName('danger')
    w.silver_help.setMinimumHeight(44)
    w.silver_help.clicked.connect(w._silver_help)
    nav.addWidget(w.silver_help)
    events = QPushButton('事件记录')
    events.setObjectName('textButton')
    events.clicked.connect(w._events)
    nav.addWidget(events, alignment=Qt.AlignmentFlag.AlignLeft)
    w.coverage = QLabel('当前未开始观察')
    w.coverage.setObjectName('muted')
    w.coverage.setWordWrap(True)
    nav.addWidget(w.coverage)
    nav.addSpacing(12)
    version = QLabel(f'本地康复  ·  {__version__}')
    version.setObjectName('muted')
    nav.addWidget(version)
    root.addWidget(sidebar)

    body = QVBoxLayout()
    body.setContentsMargins(26, 24, 26, 18)
    body.setSpacing(16)
    heading = QHBoxLayout()
    titlebox = QVBoxLayout()
    titlebox.setSpacing(6)
    w.title = QLabel('身体评估')
    w.title.setObjectName('pageTitle')
    titlebox.addWidget(w.title)
    w.subtitle = QLabel()
    w.subtitle.setObjectName('muted')
    w.subtitle.hide()  # Keep detailed scene copy available internally, not repeated below every title.
    heading.addLayout(titlebox, 1)
    w.status_badge = QLabel('相机未打开')
    w.status_badge.setObjectName('badge')
    heading.addWidget(w.status_badge, alignment=Qt.AlignmentFlag.AlignVCenter)
    body.addLayout(heading)

    person = QFrame()
    person.setObjectName('personBar')
    person_row = QHBoxLayout(person)
    person_row.setContentsMargins(14, 8, 14, 8)
    person_row.addWidget(QLabel('当前用户'))
    # Legacy ID is the same authoritative selection used by run gates. The
    # visible control selects saved profiles, not an editable identity string.
    w.participant = QLineEdit(w.participant_id, person)
    w.participant.hide()
    w.participant.setMaxLength(80)
    w.participant.textChanged.connect(lambda: w._buttons())
    w.participant_select = QComboBox()
    w.participant_select.setAccessibleName('当前用户')
    w.participant_select.setMinimumWidth(180)
    w.participant_select.setMaximumWidth(250)
    w.participant_select.currentIndexChanged.connect(w._participant_selected)
    person_row.addWidget(w.participant_select)
    w.participant_button = QPushButton('个人信息')
    w.participant_button.setObjectName('textButton')
    w.participant_button.clicked.connect(lambda: w._edit_participant())
    person_row.addWidget(w.participant_button)
    w.participant_new = QPushButton('新建用户')
    w.participant_new.setObjectName('textButton')
    w.participant_new.clicked.connect(lambda: w._edit_participant(new=True))
    person_row.addWidget(w.participant_new)
    person_row.addStretch()
    w.person_hint = QLabel('记录按用户分别保存')
    w.person_hint.setObjectName('muted')
    w.person_hint.hide()
    body.addWidget(person)
    w._refresh_participant_controls()
    w.notice = NoticeLabel()
    w.notice.setObjectName('notice')
    w.notice.setWordWrap(True)
    w.notice.setVisible(False)
    body.addWidget(w.notice)
    w._source_card(body)  # One global device selection, visible before entering any mode.

    w.pages = QStackedWidget()
    w.work_page = QWidget()
    work = QVBoxLayout(w.work_page)
    work.setContentsMargins(0, 0, 0, 0)
    work.setSpacing(12)
    split = QHBoxLayout()
    split.setSpacing(16)
    monitor = QVBoxLayout()
    monitor.setSpacing(12)
    task = QFrame()
    w.task_header = task
    task.setObjectName('taskHeader')
    taskbox = QHBoxLayout(task)
    taskbox.setContentsMargins(16, 10, 16, 10)
    title_stack = QVBoxLayout()
    title_stack.setSpacing(3)
    w.task_title = QLabel()
    w.task_title.setObjectName('sectionTitle')
    title_stack.addWidget(w.task_title)
    w.task_meta = QLabel()
    w.task_meta.setObjectName('muted')
    title_stack.addWidget(w.task_meta)
    taskbox.addLayout(title_stack, 1)
    w.catalog_button = QPushButton('更换动作')
    w.catalog_button.setObjectName('textButton')
    w.catalog_button.clicked.connect(w._show_catalog)
    taskbox.addWidget(w.catalog_button)
    monitor.addWidget(task)
    w.training_panel = TrainingControls()
    w.training_panel.control_requested.connect(lambda action, confirmed: w._send('training_control', action=action, setup_confirmed=confirmed))

    w.canvas = VideoCanvas()
    w.canvas.roi_changed.connect(w._roi_changed)
    w.video_pair = VideoPairPanel(w.canvas)
    monitor.addWidget(w.video_pair, 1)
    meta = QHBoxLayout()
    w.source_badge = QLabel('摄像头 · 未打开')
    w.source_badge.setObjectName('muted')
    meta.addWidget(w.source_badge, 1)
    w.frame_info = QLabel()
    w.frame_info.setObjectName('muted')
    meta.addWidget(w.frame_info)
    monitor.addLayout(meta)
    metrics = QHBoxLayout()
    metrics.setSpacing(10)
    w.count_card = MetricCard('完成次数', ' 次')
    w.angle_card = MetricCard('当前角度', '°')
    w.valid_card = MetricCard('有效观察', '%')
    for item in (w.count_card, w.angle_card, w.valid_card):
        metrics.addWidget(item, 1)
    w.metrics_panel = QWidget()
    w.metrics_panel.setLayout(metrics)
    metrics.setContentsMargins(0, 0, 0, 0)
    monitor.addWidget(w.metrics_panel)
    w.feedback = QLabel('打开相机，检查拍摄位置。')
    w.feedback.setObjectName('feedback')
    w.feedback.setWordWrap(True)
    # The debug checkbox remains an accessible disclosure; it is not in the
    # daily workflow. Full diagnostic evidence remains available when needed.
    w.debug_details = Disclosure('识别详情')
    w.debug_toggle = w.debug_details.toggle
    w.debug = QPlainTextEdit()
    w.debug.setReadOnly(True)
    w.debug.setMaximumHeight(125)
    w.debug_details.box.addWidget(w.debug)
    monitor.addWidget(w.debug_details)
    monitor_host = QWidget()
    monitor_host.setObjectName('scrollContent')
    monitor_host.setLayout(monitor)
    monitor.setContentsMargins(0, 0, 6, 0)
    w.monitor_scroll = QScrollArea()
    w.monitor_scroll.setWidgetResizable(True)
    w.monitor_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    w.monitor_scroll.setWidget(monitor_host)
    left = QVBoxLayout()
    left.setSpacing(10)
    left.addWidget(w.training_panel)
    left.addWidget(w.monitor_scroll, 1)
    left.addWidget(w.feedback)  # Current guidance stays visible even when the camera area scrolls.
    w.timing_readout = QLabel()
    w.timing_readout.setWordWrap(True)
    w.timing_readout.setObjectName('muted')
    w.timing_readout.hide()
    left.addWidget(w.timing_readout)
    split.addLayout(left, 1)
    w.setup_panel = w._setup_panel()
    w.setup_tabs = QTabWidget()
    w.setup_tabs.setObjectName('coachTabs')
    w.setup_tabs.tabBar().setObjectName('journeyTabs')
    w.setup_tabs.setFixedWidth(344)
    w.guide_scroll = QScrollArea()
    w.guide_scroll.setWidgetResizable(True)
    w.guide_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    w.exercise_guide = ExerciseGuide()
    w.guide_scroll.setWidget(w.exercise_guide)
    w.setup_tabs.addTab(w.guide_scroll, '动作图解')
    w.setup_tabs.addTab(w.setup_panel, '设置')
    w.journey = JourneyPanel()
    journey_scroll = QScrollArea()
    w.journey_scroll = journey_scroll
    journey_scroll.setWidgetResizable(True)
    journey_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    journey_scroll.setWidget(w.journey)
    w.setup_tabs.addTab(journey_scroll, '步骤')
    w.journey.companion.toggled.connect(w.companion.setChecked)
    w.journey.settings.clicked.connect(lambda: w.setup_tabs.setCurrentIndex(1))
    w.journey.repeat_requested.connect(w._preview)
    w.journey.another_requested.connect(w._show_catalog)
    w.journey.detail_requested.connect(w._open_latest_report)
    w.journey.automatic_requested.connect(w._open_automatic_plan)
    w.journey.guided_requested.connect(w._set_guided_mode)
    w.journey.countdown_cancelled.connect(w._cancel_start_countdown)
    w.guided_toggle.toggled.connect(w._set_guided_mode)
    w.setup_tabs.currentChanged.connect(w._refresh_guidance_visibility)
    split.addWidget(w.setup_tabs)
    # Keep the single final acknowledgement visible beside its footer action,
    # regardless of the guide/settings tab or the settings scroll position.
    w.setup_panel.widget().layout().removeWidget(w.preparation_review)
    work.addLayout(split, 1)
    sampling = QHBoxLayout()
    w.preparation_status.setStyleSheet('font-size:20px;')
    for control in (w.preparation_status, w.preparation_cancel, w.preparation_retry):
        w.setup_panel.widget().layout().removeWidget(control)
        sampling.addWidget(control, 1 if control is w.preparation_status else 0)
    work.addLayout(sampling)
    work.addWidget(w.preparation_review)

    actions = QHBoxLayout()
    actions.setSpacing(10)
    w.distance_button = QPushButton('大字指导')
    w.distance_button.clicked.connect(w._open_distance_coach)
    actions.addWidget(w.distance_button)
    w.auto_distance = QCheckBox('开始后自动放大')
    w.auto_distance.setChecked(True)
    w.auto_distance.setToolTip('正式开始评估或训练后进入大字界面；不自动开启相机或开始任务。')
    w.more_setup.box.insertWidget(0, w.auto_distance)
    w.countdown_enabled = QCheckBox('开始前 3 秒倒计时')
    w.countdown_enabled.setChecked(True)
    w.countdown_enabled.setToolTip('点击开始后先给 3 秒准备时间，可随时取消；倒计时只是界面等待，不记录数据。')
    w.more_setup.box.insertWidget(1, w.countdown_enabled)
    w.next_step_hint = QLabel()
    w.next_step_hint.setObjectName('muted')
    actions.addWidget(w.next_step_hint, 1)
    w.preview_button = QPushButton('打开预览')
    w.preview_button.clicked.connect(w._journey_next)
    w.confirm_button = QPushButton('确认准备')
    w.confirm_button.clicked.connect(w._journey_next)
    w.start_button = QPushButton('开始评估')
    w.start_button.setObjectName('primary')
    w.start_button.clicked.connect(w._journey_next)
    w.guided_pause_button = QPushButton('暂停提示')
    w.guided_pause_button.setToolTip('暂停引导提示；摄像头仍在预览，暂停期间不累计有效观察时间。')
    w.guided_pause_button.clicked.connect(w._toggle_guided_pause)
    actions.addWidget(w.guided_pause_button)
    w.self_report_button = QPushButton('记一次（我完成了）')
    w.self_report_button.setToolTip('由本人记录一次完成情况。报告会与自动观察到的次数分开列出。')
    w.self_report_button.clicked.connect(lambda: w._send('self_report'))
    actions.addWidget(w.self_report_button)
    w.stop_button = QPushButton('完成并保存')
    w.stop_button.clicked.connect(w._finish_task)
    w.privacy_button = QPushButton('停止采集')
    w.privacy_button.setToolTip('停止并释放相机；重新开始需要再次预览和确认。')
    w.privacy_button.setObjectName('danger')
    w.privacy_button.clicked.connect(lambda: w._send('privacy', reason='privacy_pause'))
    w.retry_button = QPushButton('重试保存')
    w.retry_button.clicked.connect(lambda: w._send('retry_save'))
    w.backup_button = QPushButton('备份未保存结果')
    w.backup_button.clicked.connect(w._backup_pending)
    w.discard_button = QPushButton('丢弃本次结果')
    w.discard_button.clicked.connect(w._discard_pending)
    for button in (w.preview_button, w.confirm_button, w.start_button, w.stop_button,
                   w.privacy_button, w.retry_button, w.backup_button, w.discard_button):
        button.setMinimumHeight(42)
        button.setMinimumWidth(120)
        actions.addWidget(button)
    for button in (w.self_report_button, w.guided_pause_button):
        button.setMinimumHeight(42)
    work.addLayout(actions)
    w.pages.addWidget(w.work_page)
    w._history_page()
    w._body_page()
    w.catalog = ExerciseCatalog()
    w.catalog.exercise_selected.connect(w._choose_catalog_exercise)
    w.catalog.body_requested.connect(w._show_body)
    w.pages.addWidget(w.catalog)
    w.training_hub = TrainingHub()
    w.training_hub.assessment_requested.connect(w._show_catalog)
    w.training_hub.records_requested.connect(w._show_body)
    w.training_hub.resume_requested.connect(w._resume_training_preparation)
    w.training_hub.library_requested.connect(w._open_plan_library)
    w.training_hub.automatic_requested.connect(w._open_automatic_plan)
    w.pages.addWidget(w.training_hub)
    body.addWidget(w.pages, 1)
    root.addLayout(body, 1)
    w._buttons()
