"""Synthetic provider responses for offline tests/QA, not an understanding engine.
No keyword guessing: an unlisted full clause fails the test immediately.
"""
import json
from app.agent_conversation import ModelConfig
from app.agent_statements import StatementSession as ProductionSession

CONFIG = ModelConfig('https://api.deepseek.com', 'deepseek-flash', 'synthetic-not-a-key', True)
ROWS = {'昨天妈妈头晕': {'subject': 'family',
            'time_scope': 'past',
            'statement_type': 'other',
            'concept': '头晕',
            'polarity': 'affirmed',
            'certainty': 'certain',
            'raw_text': '昨天妈妈头晕',
            'evidence_span': '昨天妈妈头晕'},
 '我今天没头晕': {'subject': 'self',
            'time_scope': 'current',
            'statement_type': 'other',
            'concept': '头晕',
            'polarity': 'negated',
            'certainty': 'certain',
            'raw_text': '我今天没头晕',
            'evidence_span': '我今天没头晕'},
 '如果我现在头晕怎么办': {'subject': 'self',
                'time_scope': 'current',
                'statement_type': 'other',
                'concept': '头晕怎么办',
                'polarity': 'hypothetical',
                'certainty': 'certain',
                'raw_text': '如果我现在头晕怎么办',
                'evidence_span': '如果我现在头晕怎么办'},
 '如果我现在头晕': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '头晕',
             'polarity': 'hypothetical',
             'certainty': 'certain',
             'raw_text': '如果我现在头晕',
             'evidence_span': '如果我现在头晕'},
 '如果我今天头晕': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '头晕',
             'polarity': 'hypothetical',
             'certainty': 'certain',
             'raw_text': '如果我今天头晕',
             'evidence_span': '如果我今天头晕'},
 '我现在可能头晕': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '头晕',
             'polarity': 'affirmed',
             'certainty': 'uncertain',
             'raw_text': '我现在可能头晕',
             'evidence_span': '我现在可能头晕'},
 '我今天可能头晕': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '头晕',
             'polarity': 'affirmed',
             'certainty': 'uncertain',
             'raw_text': '我今天可能头晕',
             'evidence_span': '我今天可能头晕'},
 '我昨天头晕': {'subject': 'self',
           'time_scope': 'past',
           'statement_type': 'other',
           'concept': '头晕',
           'polarity': 'affirmed',
           'certainty': 'certain',
           'raw_text': '我昨天头晕',
           'evidence_span': '我昨天头晕'},
 '我今天头晕': {'subject': 'self',
           'time_scope': 'current',
           'statement_type': 'other',
           'concept': '头晕',
           'polarity': 'affirmed',
           'certainty': 'certain',
           'raw_text': '我今天头晕',
           'evidence_span': '我今天头晕'},
 '头晕': {'subject': 'unknown',
        'time_scope': 'unknown',
        'statement_type': 'other',
        'concept': '头晕',
        'polarity': 'affirmed',
        'certainty': 'certain',
        'raw_text': '头晕',
        'evidence_span': '头晕'},
 '我头晕': {'subject': 'self',
         'time_scope': 'unknown',
         'statement_type': 'other',
         'concept': '头晕',
         'polarity': 'affirmed',
         'certainty': 'certain',
         'raw_text': '我头晕',
         'evidence_span': '我头晕'},
 '腿疼': {'subject': 'unknown',
        'time_scope': 'unknown',
        'statement_type': 'other',
        'concept': '腿疼',
        'polarity': 'affirmed',
        'certainty': 'certain',
        'raw_text': '腿疼',
        'evidence_span': '腿疼'},
 '我腿疼': {'subject': 'self',
         'time_scope': 'unknown',
         'statement_type': 'other',
         'concept': '腿疼',
         'polarity': 'affirmed',
         'certainty': 'certain',
         'raw_text': '我腿疼',
         'evidence_span': '我腿疼'},
 '我今天腿疼': {'subject': 'self',
           'time_scope': 'current',
           'statement_type': 'other',
           'concept': '腿疼',
           'polarity': 'affirmed',
           'certainty': 'certain',
           'raw_text': '我今天腿疼',
           'evidence_span': '我今天腿疼'},
 '妈妈今天腿疼': {'subject': 'family',
            'time_scope': 'current',
            'statement_type': 'other',
            'concept': '腿疼',
            'polarity': 'affirmed',
            'certainty': 'certain',
            'raw_text': '妈妈今天腿疼',
            'evidence_span': '妈妈今天腿疼'},
 '我明天头晕': {'subject': 'self',
           'time_scope': 'future',
           'statement_type': 'other',
           'concept': '头晕',
           'polarity': 'affirmed',
           'certainty': 'certain',
           'raw_text': '我明天头晕',
           'evidence_span': '我明天头晕'},
 '妈妈说我今天头晕': {'subject': 'unknown',
              'time_scope': 'current',
              'statement_type': 'other',
              'concept': '说我今天头晕',
              'polarity': 'affirmed',
              'certainty': 'uncertain',
              'raw_text': '妈妈说我今天头晕',
              'evidence_span': '妈妈说我今天头晕'},
 '我和妈妈今天都头晕': {'subject': 'unknown',
               'time_scope': 'current',
               'statement_type': 'other',
               'concept': '都头晕',
               'polarity': 'affirmed',
               'certainty': 'certain',
               'raw_text': '我和妈妈今天都头晕',
               'evidence_span': '我和妈妈今天都头晕'},
 '我今天不是没头晕': {'subject': 'self',
              'time_scope': 'current',
              'statement_type': 'other',
              'concept': '头晕',
              'polarity': 'affirmed',
              'certainty': 'uncertain',
              'raw_text': '我今天不是没头晕',
              'evidence_span': '我今天不是没头晕'},
 '我今天头晕吗？': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '头晕',
             'polarity': 'affirmed',
             'certainty': 'uncertain',
             'raw_text': '我今天头晕吗？',
             'evidence_span': '我今天头晕吗？'},
 '我今天不头晕': {'subject': 'self',
            'time_scope': 'current',
            'statement_type': 'other',
            'concept': '头晕',
            'polarity': 'negated',
            'certainty': 'certain',
            'raw_text': '我今天不头晕',
            'evidence_span': '我今天不头晕'},
 '我今天想问问头晕': {'subject': 'self',
              'time_scope': 'current',
              'statement_type': 'other',
              'concept': '想问问头晕',
              'polarity': 'affirmed',
              'certainty': 'uncertain',
              'raw_text': '我今天想问问头晕',
              'evidence_span': '我今天想问问头晕'},
 '我今天头晕已经好了': {'subject': 'self',
               'time_scope': 'current',
               'statement_type': 'other',
               'concept': '头晕已经好了',
               'polarity': 'affirmed',
               'certainty': 'uncertain',
               'raw_text': '我今天头晕已经好了',
               'evidence_span': '我今天头晕已经好了'},
 '我今天不舒服': {'subject': 'self',
            'time_scope': 'current',
            'statement_type': 'other',
            'concept': '不舒服',
            'polarity': 'affirmed',
            'certainty': 'uncertain',
            'raw_text': '我今天不舒服',
            'evidence_span': '我今天不舒服'},
 '请帮我记录我今天头晕': {'subject': 'self',
                'time_scope': 'current',
                'statement_type': 'other',
                'concept': '头晕',
                'polarity': 'affirmed',
                'certainty': 'certain',
                'raw_text': '请帮我记录我今天头晕',
                'evidence_span': '请帮我记录我今天头晕'},
 '我今天提到头晕': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '提到头晕',
             'polarity': 'affirmed',
             'certainty': 'uncertain',
             'raw_text': '我今天提到头晕',
             'evidence_span': '我今天提到头晕'},
 '我今天说“头晕”这个词': {'subject': 'self',
                 'time_scope': 'current',
                 'statement_type': 'other',
                 'concept': '说“头晕”这个词',
                 'polarity': 'affirmed',
                 'certainty': 'uncertain',
                 'raw_text': '我今天说“头晕”这个词',
                 'evidence_span': '我今天说“头晕”这个词'},
 '我今天担心头晕': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '担心头晕',
             'polarity': 'affirmed',
             'certainty': 'uncertain',
             'raw_text': '我今天担心头晕',
             'evidence_span': '我今天担心头晕'},
 '我昨天头晕现在好了': {'subject': 'self',
               'time_scope': 'unknown',
               'statement_type': 'other',
               'concept': '头晕现在好了',
               'polarity': 'affirmed',
               'certainty': 'uncertain',
               'raw_text': '我昨天头晕现在好了',
               'evidence_span': '我昨天头晕现在好了'},
 '我今天发烧': {'subject': 'self',
           'time_scope': 'current',
           'statement_type': 'other',
           'concept': '发烧',
           'polarity': 'affirmed',
           'certainty': 'certain',
           'raw_text': '我今天发烧',
           'evidence_span': '我今天发烧'},
 '我今天咳嗽': {'subject': 'self',
           'time_scope': 'current',
           'statement_type': 'other',
           'concept': '咳嗽',
           'polarity': 'affirmed',
           'certainty': 'certain',
           'raw_text': '我今天咳嗽',
           'evidence_span': '我今天咳嗽'},
 '我今天睡不好': {'subject': 'self',
            'time_scope': 'current',
            'statement_type': 'other',
            'concept': '睡不好',
            'polarity': 'affirmed',
            'certainty': 'certain',
            'raw_text': '我今天睡不好',
            'evidence_span': '我今天睡不好'},
 '我今天胃口不好': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '胃口不好',
             'polarity': 'affirmed',
             'certainty': 'certain',
             'raw_text': '我今天胃口不好',
             'evidence_span': '我今天胃口不好'},
 '我今天没胃口': {'subject': 'self',
            'time_scope': 'current',
            'statement_type': 'other',
            'concept': '没胃口',
            'polarity': 'affirmed',
            'certainty': 'certain',
            'raw_text': '我今天没胃口',
            'evidence_span': '我今天没胃口'},
 '我今天心情差': {'subject': 'self',
            'time_scope': 'current',
            'statement_type': 'other',
            'concept': '心情差',
            'polarity': 'affirmed',
            'certainty': 'certain',
            'raw_text': '我今天心情差',
            'evidence_span': '我今天心情差'},
 '我今天头有点沉': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '头有点沉',
             'polarity': 'affirmed',
             'certainty': 'certain',
             'raw_text': '我今天头有点沉',
             'evidence_span': '我今天头有点沉'},
 '昨天摔了一跤': {'subject': 'unknown',
            'time_scope': 'past',
            'statement_type': 'other',
            'concept': '摔了一跤',
            'polarity': 'affirmed',
            'certainty': 'certain',
            'raw_text': '昨天摔了一跤',
            'evidence_span': '昨天摔了一跤'},
 '我昨天摔了一跤': {'subject': 'self',
             'time_scope': 'past',
             'statement_type': 'other',
             'concept': '摔了一跤',
             'polarity': 'affirmed',
             'certainty': 'certain',
             'raw_text': '我昨天摔了一跤',
             'evidence_span': '我昨天摔了一跤'},
 '妈妈今天发烧': {'subject': 'family',
            'time_scope': 'current',
            'statement_type': 'other',
            'concept': '发烧',
            'polarity': 'affirmed',
            'certainty': 'certain',
            'raw_text': '妈妈今天发烧',
            'evidence_span': '妈妈今天发烧'},
 '如果明天发烧': {'subject': 'unknown',
            'time_scope': 'future',
            'statement_type': 'other',
            'concept': '发烧',
            'polarity': 'hypothetical',
            'certainty': 'certain',
            'raw_text': '如果明天发烧',
            'evidence_span': '如果明天发烧'},
 '我今天没有咳嗽': {'subject': 'self',
             'time_scope': 'current',
             'statement_type': 'other',
             'concept': '咳嗽',
             'polarity': 'negated',
             'certainty': 'certain',
             'raw_text': '我今天没有咳嗽',
             'evidence_span': '我今天没有咳嗽'}}


def payload(text):
    return {'statements': [ROWS[part] for part in text.split('，')]}


def transport(config, messages):
    assert config == CONFIG
    return json.dumps(payload(messages[-1]['content']), ensure_ascii=False)


class StatementSession(ProductionSession):
    """Inject the explicit offline provider into existing persistence/UI tests."""
    def turn(self, text, **kwargs):
        kwargs.setdefault('config', CONFIG)
        kwargs.setdefault('transport', transport)
        return super().turn(text, **kwargs)
